### ISSUE TITLE
Checklist On Various Bugs and Feature Request needs to be worked upon immediate basis to make kiwi flawless gold standard browser on android

### ISSUE THREAD

**Issue by tathastu871** [kiwibrowser/src.next#1150]
I Personally Never Thought I Will Use Kiwi As Daily Browser. But Due To Ignorance Of Brave Devs After 3 Years Of Turmoil I Finally Switched To Kiwi. Adapted Myself To Kiwi UI And Now Its 1 Year Since. 

**But Here For Kiwi Same Story All Devs Just Spend Time In Adding Complex Features To Their Browser.**

Now That I Have And Many More Brave Users That I Know Have Started Using Kiwi I Would Love To See Kiwi As Gold Standard On Android Browser, Atleast In Terms Of Basic Browser Core Features

**But Some Basic Features That Makes A Browser A Browser**

**Bugs And Feature Request**

- [ ] 1) Quick Tab Switching 
        ->  https://Github.Com/Kiwibrowser/Src.Next/Issues/1147
       ->  https://Github.Com/Kiwibrowser/Src.Next/Issues/1137
        **In Settings Where We Can Toggle On/Off There Whether All Links Thats Have Target '_Blank' Be Opened In Same Group Tab -> Right Next To Currently Opened Tab**

-[ ] 2) Default **Extension Page And Devtools Page** Must Open In Group Next To Current Tab That Allows For Quick Switching Via Group Bubble  And Improve Productivity

-[ ] 3) **Stale Devtools Page**  Whose Connection To Opener Tab Is Closed Due To Closing Ad Reopening Of Kiwi Must Be Discarded Automatically
**Because I Have Experienced That When Stale Devtools Page Are Open I See Network Connectivity Issue,  Means When I Try To Open Webpage It Doesnt Open And Also The 4G In My Android Notification Toolbar Keeps Greying Out And Fluctuating And It Affects Other Browsers On My Device  But As Soon As I Close The Kiwi Other Browsers Starts Working Normally And Internet Connectivity Gets Stable.
I Ruled Out That Closing The Stale Devtools Page Also Restores Normal Functioning

- [ ] 4) Increase The Recent Tabs Time Period
**In Case Of Accidental Crash (When Enabling Bottim Toolbar For Example) Kiwi Closes All Tabs And Resets In That Case We Have To Relaunch Kiwi And Immediately Click Recent Tabs And Restore But It Needs To Be Done Quickly Upon Restart If Not Or Of We Open New Tab / Url  Kiwi Removes All Previous Tabs Cache From Most Recemt Tab Menu And We Cannot Restore And Lost 

-[ ] 5) **Bug**: Fullscreen Video Previous Tab Overlay  : Also In Other Chromium Based Browsers. When On Certain Movie Or Video Site I Fullscreen My Video And It Shifts To Landscape Mode The Previous Tab As Image Is Seen On Half Of Device Screen Covering Partial Video

https://Github.Com/Kiwibrowser/Src.Next/Issues/469
Not Fixed In Latest Kiwi Build

-[ ] 6) **Exit/Quit Button Bug** Closes All Tabs When Exit
-> https://Github.Com/Kiwibrowser/Src.Next/Issues/1123

-[ ] 7) External Download Manager (Termux Support) - Possible We Can Send Final Download Link To Termux  App Maybe Along With Cookies So That We Can Use Wget/Curl/Aria2C Like Command Line Tools For For Parallel Multithreaded Download

-[ ] 8) Full Export Import Of Whole Browser Profile Without Root (History, Bookmarks, Opened Tabs, Passwords, Settings) So That We Can Backup And Restore (If Possible Auto+Periodic)

-[ ] 9) Heavy Lag When Switching Back To Kiwi 
https://Github.Com/Kiwibrowser/Src.Next/Issues/1145

-[ ] 10) Group Tab Api Support Extensions

11) Ease Of Ui Accessibility 

- [ ] A) **One Hand Browsing - Bottom Toolbar.** In Kiwi If In Setting I **Enable Bottom Toolbar And Relaunch It Closes All Tabs Just Resets Everything** It Occured 3 Times With Me And Also There Is Git Issue If Dev Had Read And Not Ignored. Right Now In Latest Kiwi Version I Had 500 Tabs Opened I Want To Enable Bottom Toolbar But Not Willing To Take Risk Of Losing Tabs

- [ ] B) **Ability To Select All Tabs So We Can Backup Them** (Related To Above If I Can Backup Opened Tabs I Can Test If Enabling Bottom Toolbar Still Closes Tabs (Risk)
-> https://Github.Com/Kiwibrowser/Src.Next/Issues/1125

- [ ] C) Quick Add Bookmark (Brave Allows For Justquick Bookmarking Directly From Toolbar) Just One Button Click, 

- [ ] D) Quickly Open New Tab From Toolbar

- [ ] E) Bookmark Sorting  And Create Bookmark Folder  And **Select All Bookmarks In Folder And  Bulk Delete Them** (Most Needed)

https://Github.Com/Kiwibrowser/Src.Next/Assets/65007212/420Ca422-989B-42A8-99B3-62C9A82B1Dd2

- [ ] F)  When All Tabs Are Closed Automatically Open New Tab. Lemur Has This Settings. Because After Closing All Tabs Its Anmoying To Click Menu And Them Add New Tab.

**Comment by YouSummoner** [comment]
Two More: A) The inbuilt dark mode is broken and keeps inverting colours of web contents. #968  
B) The browser keeps disabling the monet theming for some reason. #969

**Comment by Haerbin23456** [comment]
I just wonder: are the maintainers still alive? Or they've forgotten their passwords?

**Comment by phanirithvij** [comment]
https://github.com/kiwibrowser/src.next/issues/1101#issuecomment-2016552061
